name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Angular project
      - name: Build Angular app
        run: npm run build -- --output-path=dist --base-href="/grenadepong/"

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ng deploy --repo=https://github.com/cholnhial/grenadepong.git --no-silent --dir=dist/browser --name="Chol Nhial" --email=chol.nhial.chol@gmail.com
